// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TripApi.Models
{
    public partial class Trip
    {
        public Trip()
        {
            ClientTrip = new HashSet<ClientTrip>();
            CountryTrip = new HashSet<CountryTrip>();
        }

        public int IdTrip { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime DateFrom { get; set; }
        public DateTime DateTo { get; set; }
        public int MaxPeople { get; set; }

        public virtual ICollection<ClientTrip> ClientTrip { get; set; }
        public virtual ICollection<CountryTrip> CountryTrip { get; set; }
    }
}